### ISSUE TITLE
suggestion for the centos on odroid c2 wiki

### ISSUE THREAD

**Issue by jperrin** [umiddelb/aarch64#1]
I found your wiki for using centos with the odroid c2, https://github.com/umiddelb/aarch64/wiki/Install-CentOS-7-on-the-ODROID-C2

Very nice writeup. I had one minor suggestion for it that simplifies the losetup step. I'm somewhat partial to using `kpartx` which handles identifying the partition offsets and makes the device available via loopback. There's an example of using it in the README at  http://mirror.centos.org/altarch/7/isos/aarch64/ReadMe.txt

Thanks again for the write-up!

**Comment by umiddelb** [comment]
Thank you very much! Indeed this is much easier and I wasn't aware of `kpartx` before.

**Comment by umiddelb** [comment]
Btw. I'm trying to adapt my [automated setup procedure](https://github.com/umiddelb/z2d) in order to create a CentOS install for my various ARM devices. The setup procedure would be much easier if you / CentOS consider to provide a rootfs only tar archive as well (like the Ubuntu people do with [Ubuntu Core](https://wiki.ubuntu.com/Core)).

Another interesting addition would be a script which checks the presence of necessary kernel features (from the CentOS perspective), like [check-config.sh](https://github.com/umiddelb/armhf/wiki/Installing,-running,-using-docker-on-armhf-%28ARMv7%29-devices#see-whats-missing) does for Docker related requirements, because many ARM boards are still not able to run a mainline kernel.

**Comment by jperrin** [comment]
I'll consider doing a rootfs build. I had initially NOT done one to try to help force the 'use UEFI' idea, but as much as I want to push UEFI, I want people using our distro as well. 

As to the mainline kernel bit, yes. That's a bit of pain where I'm not overly happy about the current state of things, mostly because the vendor kernels almost never get security updates, or any sort of update for that matter.

**Comment by umiddelb** [comment]
> I'll consider doing a rootfs build. 

Cool, beside Ubuntu, [Archlinux](https://archlinuxarm.org/platforms/armv8/generic) is providing this as well (ARMv8 only). 

> I had initially NOT done one to try to help force the 'use UEFI' idea, but as much as I want to push UEFI, I want people using our distro as well.

I'm not happy with u-boot's current status, too. I started to [consolidate the u-boot implementations](https://github.com/umiddelb/u-571) I was faced with in order to archive some common boot behaviour using u-boot macro language. And u-boot will remain reality for SBCs derived from Mobile/Tablet SoCs as long as [UEFI is only indented for ARM server platforms](http://www.linaro.org/blog/when-will-uefi-and-acpi-be-ready-on-arm/). And chainloading UEFI on u-boot (like chainloading GRUB on u-boot) doesn't sound very reasonable.

> That's a bit of pain where I'm not overly happy about the current state of things, mostly because the vendor kernels almost never get security updates, or any sort of update for that matter.

I totally agree. The consideration user base vs. rigour applies here as well. But having this check would vastly improve the adaption of CentOS for this kind of devices.

**Comment by umiddelb** [comment]
And sometimes the rhelsa kernel sources might be too old for recent ARM mainlining efforts.

**Comment by umiddelb** [comment]
In the meantime, I got CentOS 7 up and running on the PINE64+(ARMv8) and the ODROID-XU4(ARMv7) as well. It seems that the rootfs setup and package availability differ between ARMv7 and ARMv8 (e.g. ARMv7 doesn't include a Docker package and using the f23's Docker package turns the CentOS7 userland into something hybrid). There is no EPEL for ARM, isn't it?

**Comment by jperrin** [comment]
No epel yet, though that will happen. Excellent news on the pine64! I'm traveling this week and part of next, but I'll try to get the rootfs built for you to test. Thanks again for your work.

**Comment by jperrin** [comment]
Out of curiosity, do you have the pine64 image instructions available someplace? I'd like to see if we can promote it to get some more traction for aarch64. Also, I'd like to send you some CentOS swag for the work you've put in on this, if you wouldn't mind emailing me privately to work out the details.

**Comment by umiddelb** [comment]
> No epel yet, though that will happen.

I've seen the announcement for EPEL on aarch64 and now subscribed to the [arm-dev mailing list](https://lists.centos.org/pipermail/arm-dev/). So we may close this conversation here.
