### ISSUE TITLE
Centos on Odroid C2

### ISSUE THREAD

**Issue by markVnl** [umiddelb/aarch64#2]
Hi Uli,

First of all, thanx for the write up of Install-CentOS-7-on-your-favourite-ARMv8-ARM64-AArch64-board
(https://github.com/umiddelb/aarch64/wiki/Install-CentOS-7-on-your-favourite-ARMv8-ARM64-AArch64-board)
Second: I just want to share my experience with Centos on a ordroid C2.
Third: I’m just an enthusiastic amateur with limited experience of the hole RHEL family. 
(**So for all readers beware:** I’m **not** sure the following is completely accurate.)

I found the Archlinux-Arm (Alarm) the best base to merge with a Centos rootfs. It comes with a initramfs instead of a initrd. Dracut happily plays with this Alarm initramf. Downside is complicated updating of the kernel, the init ramfs is created during the update of the kernel. Especially with a eMMC module.
My workaround is a “multi” boot setup containing a boot partition (u-boot and the kernel) and multiple partitions with rootfs’s. by editing setenv bootargs in boot.ini you can choose which distro starts (root=/dev/mmcblk0pX). One of them is arch-arm where the kernel can be updated, then you must distribute the kernel modules to all other partitions/distros. 

IMO It’s recommendable to disable kernel updates if you use the rootfs provided by  Alternative Architecture Centos SIG.

Do you know if someone is working on a spec-file to build a kernel?

**Comment by umiddelb** [comment]
Hi Mark,

thank you for your remarks. You might have noticed the [automated CentOS build procedure for the C2](https://github.com/umiddelb/z2d/tree/master/odroid-c2). It combines the u-boot firmware from HK, the CentOS Aarch64 userland and a kernel image which I have build out of the [GH sources](https://github.com/hardkernel/linux/tree/odroidc2-3.14.y). The initrd 'image' is created by 

```
update-initramfs -c -k <version>
```

instead of using dracut. I don't know if it makes a big difference for the actual image (should be a compressed cpio archive IHMO). HK provides some configuration support for initramfs, that's the reason why I haven't tried dracut so far.

I'm not a big fan of the cfgload/boot.ini mechanism HK is using by default. I prefer an interactive u-boot shell which gives me the flexibility to boot a different configuration (including kernel, rootfs and other settings). I started to hack [my own set of u-boot macros](https://github.com/umiddelb/u-571). 

I don't see the difficulties updating the kernel in combination with an eMMC module, may be I've missed your point.

The automated distro kernel updates don't overwrite the actual kernel, so they don't cause any harm.

There should be a spec-file at least for the distro kernel (which I cannot use for the C2). 

Cheers
Uli

P.S.:
You may consider to subscribe to the [CentOS Arm-dev ML](https://lists.centos.org/mailman/listinfo/arm-dev), if you haven't already.
